#!/usr/bin/env bash
# Linux backup wrapper. Run as the account that owns the Hydro installation.
set -euo pipefail
umask 077

usage() {
  cat <<'EOF'
Usage: backup-hydro.sh [--output-dir ABSOLUTE_DIR] [--file-store ABSOLUTE_DIR]
                       [--caddy-config ABSOLUTE_FILE] [--hydro-bin COMMAND_OR_ABSOLUTE_FILE]

Defaults: output-dir=/data/backups/swpu-oj; file-store=/data/file; hydro-bin=hydrooj.
Hydro state is read from the current user's ~/.hydro (and HYDRO_PROFILE, if set).
Caddy config defaults to ~/.hydro/Caddyfile, then /etc/caddy/Caddyfile.
Runs hydrooj backup --withAddons, validates the ZIP, saves configuration/custom
assets and SHA256SUMS. No old backups are deleted; no services are stopped.
EOF
}

output_dir=/data/backups/swpu-oj
file_store=/data/file
hydro_bin=hydrooj
caddy_config=
while (($#)); do
  case "$1" in
    --output-dir|--file-store|--caddy-config|--hydro-bin)
      (($# >= 2)) || { printf 'Missing value for %s\n' "$1" >&2; exit 64; }
      case "$1" in
        --output-dir) output_dir=$2 ;;
        --file-store) file_store=$2 ;;
        --caddy-config) caddy_config=$2 ;;
        --hydro-bin) hydro_bin=$2 ;;
      esac
      shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) printf 'Unknown argument: %s\n' "$1" >&2; usage >&2; exit 64 ;;
  esac
done

for binary in flock tar unzip sha256sum mktemp realpath; do
  command -v "$binary" >/dev/null || { printf 'Required command missing: %s\n' "$binary" >&2; exit 69; }
done
hydro_bin=$(command -v "$hydro_bin") || { printf 'hydrooj executable not found\n' >&2; exit 69; }
hydro_bin=$(realpath -- "$hydro_bin")
hydro_home=${HOME:?HOME must identify the Hydro installation owner}/.hydro
if [[ -n ${HYDRO_PROFILE:-} ]]; then
  hydro_home=$hydro_home/profiles/$HYDRO_PROFILE
fi
[[ -r "$hydro_home/config.json" ]] || { printf 'Hydro config.json is missing or unreadable\n' >&2; exit 66; }
hydro_home=$(realpath -- "$hydro_home")
hydro_state_root=$(realpath -- "$HOME/.hydro")
[[ $output_dir == /* ]] || { printf 'output-dir must be absolute\n' >&2; exit 64; }
output_dir=$(realpath -m -- "$output_dir")
case "$output_dir/" in
  "$hydro_state_root/"*) printf 'output-dir must be outside the Hydro state directory\n' >&2; exit 64 ;;
esac
[[ $file_store == /* ]] || { printf 'file-store must be absolute\n' >&2; exit 64; }
file_store=$(realpath -m -- "$file_store")
case "$output_dir/" in
  "$file_store/"*) printf 'output-dir must be outside the Hydro file store (%s): the backup ZIP would include its own logs\n' "$file_store" >&2; exit 64 ;;
esac
runtime_config=$HOME/.config/hydro
if [[ -d "$runtime_config" ]]; then
  runtime_config=$(realpath -- "$runtime_config")
  case "$output_dir/" in
    "$runtime_config/"*) printf 'output-dir must be outside ~/.config/hydro\n' >&2; exit 64 ;;
  esac
fi
if [[ -z "$caddy_config" ]]; then
  if [[ -r "$HOME/.hydro/Caddyfile" ]]; then caddy_config=$HOME/.hydro/Caddyfile
  else caddy_config=/etc/caddy/Caddyfile; fi
fi
[[ $caddy_config == /* && -f $caddy_config && -r $caddy_config ]] || {
  printf 'Caddy config must be an absolute, readable file; use --caddy-config\n' >&2; exit 66;
}
caddy_config=$(realpath -- "$caddy_config")

mkdir -p -- "$output_dir"
exec 9>"$output_dir/.backup.lock"
flock -n 9 || { printf 'Another backup is running for this output-dir\n' >&2; exit 75; }
run_dir=$(mktemp -d "$output_dir/.pending-$(date -u +%Y%m%dT%H%M%SZ)-XXXXXX")
trap 'result=$?; if ((result != 0)); then printf "Backup failed (exit %s); incomplete files retained in %s\n" "$result" "$run_dir" >&2; fi' EXIT

# Hydro v5 logs its MongoDB URI. Keep its full output in a private file.
if (cd "$run_dir" && "$hydro_bin" backup --withAddons) >"$run_dir/hydro-backup.log" 2>&1; then
  :
else
  result=$?
  printf 'Hydro backup failed; inspect the private hydro-backup.log locally\n' >&2
  exit "$result"
fi
shopt -s nullglob
archives=("$run_dir"/backup-*.zip)
if ((${#archives[@]} != 1)) || [[ ! -s ${archives[0]} ]]; then
  printf 'Hydro did not produce exactly one nonempty backup ZIP\n' >&2; exit 65
fi
unzip -tq "${archives[0]}" >"$run_dir/validation.log" 2>&1
unzip -Z1 "${archives[0]}" >"$run_dir/backup-members.txt"
if ! grep -Eq '^dump/.*\.bson$' "$run_dir/backup-members.txt" || ! grep -q '^file/' "$run_dir/backup-members.txt"; then
  printf 'Backup ZIP is missing database BSON or the file storage directory\n' >&2; exit 65
fi

# static/ is generated by Hydro. Preserve configuration, addons, custom/, judge.yaml,
# env and other state without printing their contents or following external symlinks.
tar -czf "$run_dir/hydro-state.tar.gz" --exclude='./static' --exclude='./profiles/*/static' -C "$hydro_state_root" .
extra_files=(hydro-state.tar.gz Caddyfile hydro-backup.log validation.log backup-members.txt)
cp -- "$caddy_config" "$run_dir/Caddyfile"
if [[ -d "$runtime_config" ]]; then
  tar -czf "$run_dir/runtime-config.tar.gz" -C "$runtime_config" .
  extra_files+=(runtime-config.tar.gz)
fi
{
  printf 'created_utc=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'hydro_state_path=%q\n' "$hydro_state_root"
  printf 'active_hydro_path=%q\n' "$hydro_home"
  printf 'runtime_config_path=%q\n' "$runtime_config"
  printf 'caddy_config_path=%q\n' "$caddy_config"
  printf 'hydro_executable=%q\n' "$hydro_bin"
  printf 'profile=%q\n' "${HYDRO_PROFILE:-}"
  printf 'retention=Keep 7 daily, 4 weekly, 3 monthly complete copies; manual review only.\n'
  printf 'consistency=Live backup; database/files are not an atomic cross-storage snapshot.\n'
  printf 'external_files=Check addon links and Caddy imports; external targets need separate backups.\n'
} >"$run_dir/manifest.txt"
extra_files+=(manifest.txt)
archive_name=${archives[0]##*/}
(cd "$run_dir" && sha256sum -- "$archive_name" "${extra_files[@]}" > SHA256SUMS)
final_dir=$output_dir/backup-${run_dir##*/.pending-}
[[ ! -e "$final_dir" ]] || { printf 'Final backup directory already exists\n' >&2; exit 73; }
mv -T -- "$run_dir" "$final_dir"
printf 'Backup complete: %s\n' "$final_dir"
printf 'No old copies removed. Copy the full directory off this server and test restoration.\n'
